spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      grpc:
        enabled: false
      routes:
        - id: user-service
          uri: http://user-service:8081
          predicates:
            - Path=/api/v1/users/**
          filters:
            - StripPrefix=1


server:
  port: 8080

eureka:
  client:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

app:
  firebase:
    enabled: true
    service-account-path: /app/firebase-service-account.json

logging:
  level:
    com.yuesaohub.platform: INFO
    org.springframework.cloud.gateway: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
