spring:
  application:
    name: api-gateway
  
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      grpc:
        enabled: false
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/users/**
          filters:
            - StripPrefix=1
        - id: public-health
          uri: http://localhost:8080
          predicates:
            - Path=/health

eureka:
  client:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    com.yuzao.platform: ${LOG_LEVEL:INFO}
    org.springframework.cloud.gateway: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

app:
  firebase:
    enabled: ${FIREBASE_ENABLED:false}
    service-account-path: ${FIREBASE_SERVICE_ACCOUNT_PATH:./firebase-service-account.json}

server:
  port: 8080
